import "./globals.css";

import { theme } from "@/libs/theme";
import { MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { ModalsProvider } from "@mantine/modals";
import type { Metadata } from "next";

import ProgressBarProvider from "@/providers/ProgressBarProvider";
import { NextAuthProvider } from "@/providers/auth-provider";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await auth();

  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
          <NextAuthProvider>
            <Notifications position="top-right" />
            <ModalsProvider />
            <ProgressBarProvider>{children}</ProgressBarProvider>
          </NextAuthProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
