import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";

import { theme } from "@/libs/theme";
import { MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { ModalsProvider } from "@mantine/modals";
import type { Metadata } from "next";
import MainLayout from "@/components/MainLayout/MainLayout";
import { Suspense } from "react";
import Loading from "./loading";
import ProgressBarProvider from "@/components/ProgressBar/ProgressBarProvider";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
          <Notifications position="top-right" />
          <ModalsProvider />
          <MainLayout>
            <Suspense fallback={<Loading />}>
              <ProgressBarProvider>{children}</ProgressBarProvider>
            </Suspense>
          </MainLayout>
        </MantineProvider>
      </body>
    </html>
  );
}
